# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 48
    bpp: 8
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F0E4E",  # mdi-thermometer
      "\U000F0143",  # mdi-chevron-up
      "\U000F0140",  # mdi-chevron-down
      "\U000F0717",  # mdi-snowflake
      "\U000F0238",  # mdi-fire
      "\U000F058E",  # mdi-water-percent
      "\U000F040A",  # mdi-play
      "\U000F03E4",  # mdi-pause
      "\U000F04AD",  # mdi-skip-next
      "\U000F04AE",  # mdi-skip-previous
      "\U000F057E",  # mdi-volume-high
      "\U000F075A",  # mdi-music
      "\U000F07AE",  # mdi-cctv
      "\U000F0450",  # mdi-refresh
      "\U000F004D",  # mdi-arrow-left
      ]

  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font_small
    size: 28
    bpp: 8
    glyphs: [
      "\U000F058E",  # mdi-water-percent
      "\U000F0E4E",  # mdi-thermometer
      "\U000F0717",  # mdi-snowflake
      "\U000F0238",  # mdi-fire
      ]

# Map icons to names
substitutions:
  lightbulb:      "\U000F0335"
  nightlight:     "\U000F1A4C"
  thermometer:    "\U000F0E4E"
  chevron_up:     "\U000F0143"
  chevron_down:   "\U000F0140"
  snowflake:      "\U000F0717"
  fire:           "\U000F0238"
  water_percent:  "\U000F058E"
  play:           "\U000F040A"
  pause:          "\U000F03E4"
  skip_next:      "\U000F04AD"
  skip_previous:  "\U000F04AE"
  volume_high:    "\U000F057E"
  music:          "\U000F075A"
  cctv:           "\U000F07AE"
  refresh:        "\U000F0450"
  arrow_left:     "\U000F004D"
